# Chapter 1: GemPy Basic

In this first example, we will show how to construct a first basic model and the main objects and functions. First we import gempy:

In [1]:
# These two lines are necessary only if gempy is not installed
import sys, os
sys.path.append("../..")

# Importing gempy
import gempy as gp

# Embedding matplotlib figures into the notebooks
%matplotlib inline

# Aux imports
import numpy as np

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

In [2]:
# Importing the data from csv files and settign extent and resolution
geo_data = gp.create_data([0,2000,0,2000,-2000,0],[ 20,20,20],
                         path_o = os.pardir+"/input_data/FabLessPoints_Foliations.csv",
                         path_i = os.pardir+"/input_data/FabLessPoints_Points.csv")

here
there

In [12]:
geo_data.orientations[geo_data._columns_o_num] = geo_data.orientations[geo_data._columns_o_num].astype('float', errors='ignore', copy=True)

In [13]:
geo_data.orientations.dtypes

X                   float64
Y                   float64
Z                   float64
G_x                 float64
G_y                 float64
G_z                 float64
dip                 float64
azimuth             float64
polarity            float64
formation            object
series               object
order_series          int64
isFault                bool
formation_number      int64
annotations          object
dtype: object

In [23]:
geo_data.orientations.columns

Index(['X', 'Y', 'Z', 'G_x', 'G_y', 'G_z', 'dip', 'azimuth', 'polarity',
       'formation', 'series', 'order_series', 'isFault', 'formation_number',
       'annotations'],
      dtype='object')

In [22]:
import pandas as pn
pn.

In [3]:
geo_data.interactive_df_open(itype='all')

../../gempy/data_management.py:265: UserWarning: When itype is 'all' Add Row does not work. If needed try using interfaces or orientations instead
  warnings.warn('When itype is \'all\' Add Row does not work. If needed try using interfaces or orientations'

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defaultColumnWidth': 150, 'rowHeight': 28, 'enableColumnReorder': False, 'enableTextSelectionOnCells': True, 'editable': True, 'autoEdit': False, 'explicitInitialization': True, 'maxVisibleRows': 15, 'minVisibleRows': 8, 'sortable': True, 'filterable': True, 'highlightSelectedCell': False, 'highlightSelectedRow': True}, precision=5, show_toolbar=True)

In [4]:
n_df = geo_data.interactive_df_get_changed_df(only_selected=False)

In [5]:
n_df

                      G_x    G_y       G_z       X     Y       Z azimuth  \
interfaces   0        NaN    NaN       NaN     800   200   -1400     NaN
             1        NaN    NaN       NaN     800  1800   -1400     NaN
             2        NaN    NaN       NaN     600  1000   -1050     NaN
             3        NaN    NaN       NaN     300  1000    -950     NaN
             4        NaN    NaN       NaN    2000  1000   -1275     NaN
             5        NaN    NaN       NaN    1900  1000   -1300     NaN
             6        NaN    NaN       NaN    1300  1000   -1100     NaN
             7        NaN    NaN       NaN    1600  1000   -1200     NaN
             8        NaN    NaN       NaN    1750  1000   -1250     NaN
             9        NaN    NaN       NaN    1000    25   -1050     NaN
             10       NaN    NaN       NaN    1000   100   -1100     NaN
             11       NaN    NaN       NaN    1000  1975   -1050     NaN
             12       NaN    NaN       NaN    1000  1900   -1100     NaN
             13       NaN    NaN       NaN    1150  1000   -1050     NaN
             14       NaN    NaN       NaN     600  1000    -650     NaN
             15       NaN    NaN       NaN    1300  1000    -700     NaN
             16       NaN    NaN       NaN    1600  1000    -800     NaN
             17       NaN    NaN       NaN    1900  1000    -900     NaN
             18       NaN    NaN       NaN    2000  1000    -875     NaN
             19       NaN    NaN       NaN     900  1000    -750     NaN
             20       NaN    NaN       NaN     600  1000   -1350     NaN
             21       NaN    NaN       NaN     300  1000   -1250     NaN
             22       NaN    NaN       NaN    2000  1000   -1575     NaN
             23       NaN    NaN       NaN    1300  1000   -1400     NaN
             24       NaN    NaN       NaN    1600  1000   -1500     NaN
             25       NaN    NaN       NaN    1750  1000   -1550     NaN
             26       NaN    NaN       NaN    1000  1000   -1300     NaN
             27       NaN    NaN       NaN    1900  1000   -1600     NaN
             28       NaN    NaN       NaN    1000  1000   -1000     NaN
             29       NaN    NaN       NaN     900  1000   -1300     NaN
             30       NaN    NaN       NaN    1100  1000    -700     NaN
             31       NaN    NaN       NaN    1200  1000    -400     NaN
             32       NaN    NaN       NaN     800  1000   -1600     NaN
             33       NaN    NaN       NaN    2000  1000    -775     NaN
             34       NaN    NaN       NaN    1600  1000    -700     NaN
             35       NaN    NaN       NaN    1900  1000    -800     NaN
             36       NaN    NaN       NaN     900  1000    -650     NaN
             37       NaN    NaN       NaN     600  1000    -550     NaN
             38       NaN    NaN       NaN    1300  1000    -600     NaN
             39       NaN    NaN       NaN     NaN   NaN     NaN     NaN
orientations 0   0.316229  1e-07  0.948683    1450  1000   -1150      90
             1  -0.948683  1e-07  0.316229  917.45  1000 -1135.4     270

                    dip           formation polarity         series
interfaces   0      NaN           Reservoir      NaN  Default serie
             1      NaN           Reservoir      NaN  Default serie
             2      NaN           Reservoir      NaN  Default serie
             3      NaN           Reservoir      NaN  Default serie
             4      NaN           Reservoir      NaN  Default serie
             5      NaN           Reservoir      NaN  Default serie
             6      NaN           Reservoir      NaN  Default serie
             7      NaN           Reservoir      NaN  Default serie
             8      NaN           Reservoir      NaN  Default serie
             9      NaN           Reservoir      NaN  Default serie
             10     NaN           Reservoir      NaN  Default serie
             11     NaN           Reservoir      NaN  Default serie
             12     NaN           Reservoir      NaN  Default serie
             13     NaN           Reservoir      NaN  Default serie
             14     NaN                Seal      NaN  Default serie
             15     NaN                Seal      NaN  Default serie
             16     NaN                Seal      NaN  Default serie
             17     NaN                Seal      NaN  Default serie
             18     NaN                Seal      NaN  Default serie
             19     NaN                Seal      NaN  Default serie
             20     NaN           Overlying      NaN  Default serie
             21     NaN           Overlying      NaN  Default serie
             22     NaN           Overlying      NaN  Default serie
             23     NaN           Overlying      NaN  Default serie
             24     NaN           Overlying      NaN  Default serie
             25     NaN           Overlying      NaN  Default serie
             26     NaN           Overlying      NaN  Default serie
             27     NaN           Overlying      NaN  Default serie
             28     NaN           MainFault      NaN  Default serie
             29     NaN           MainFault      NaN  Default serie
             30     NaN           MainFault      NaN  Default serie
             31     NaN           MainFault      NaN  Default serie
             32     NaN           MainFault      NaN  Default serie
             33     NaN  SecondaryReservoir      NaN  Default serie
             34     NaN  SecondaryReservoir      NaN  Default serie
             35     NaN  SecondaryReservoir      NaN  Default serie
             36     NaN  SecondaryReservoir      NaN  Default serie
             37     NaN  SecondaryReservoir      NaN  Default serie
             38     NaN  SecondaryReservoir      NaN  Default serie
             39     NaN            basement      NaN        Default
orientations 0   18.435           Reservoir        1  Default serie
             1   71.565           MainFault        1  Default serie

In [5]:
geo_data.set_new_df(n_df)

there
there
         X       Y         Z       G_x           G_y       G_z     dip  \
0  1450.00  1000.0 -1150.000  0.316229  1.000000e-07  0.948683  18.435
1   917.45  1000.0 -1135.398 -0.948683  1.000000e-07  0.316229  71.565

   azimuth  polarity  formation         series  order_series  isFault  \
0     90.0       1.0  Reservoir  Default serie             1    False
1    270.0       1.0  MainFault  Default serie             1    False

   formation_number                      annotations
0                 1  ${\bf{x}}_{\beta \,{\bf{1}},0}$
1                 2  ${\bf{x}}_{\beta \,{\bf{2}},0}$
there
          X       Y         Z       G_x           G_y       G_z     dip  \
0    800.00   200.0 -1400.000       NaN           NaN       NaN     NaN
22   800.00  1800.0 -1400.000       NaN           NaN       NaN     NaN
23   600.00  1000.0 -1050.000       NaN           NaN       NaN     NaN
24   300.00  1000.0  -950.000       NaN           NaN       NaN     NaN
25  2000.00  1000.0 -1275.000       NaN           NaN       NaN     NaN
26  1900.00  1000.0 -1300.000       NaN           NaN       NaN     NaN
27  1300.00  1000.0 -1100.000       NaN           NaN       NaN     NaN
28  1600.00  1000.0 -1200.000       NaN           NaN       NaN     NaN
29  1750.00  1000.0 -1250.000       NaN           NaN       NaN     NaN
30  1450.00  1000.0 -1150.000  0.316229  1.000000e-07  0.948683  18.435
31  1000.00    25.0 -1050.000       NaN           NaN       NaN     NaN
32  1000.00  1975.0 -1050.000       NaN           NaN       NaN     NaN
33  1000.00  1900.0 -1100.000       NaN           NaN       NaN     NaN
34  1150.00  1000.0 -1050.000       NaN           NaN       NaN     NaN
40  1000.00   100.0 -1100.000       NaN           NaN       NaN     NaN
11  2000.00  1000.0  -775.000       NaN           NaN       NaN     NaN
12  1600.00  1000.0  -700.000       NaN           NaN       NaN     NaN
13  1900.00  1000.0  -800.000       NaN           NaN       NaN     NaN
14   900.00  1000.0  -650.000       NaN           NaN       NaN     NaN
15   600.00  1000.0  -550.000       NaN           NaN       NaN     NaN
16  1300.00  1000.0  -600.000       NaN           NaN       NaN     NaN
1   1300.00  1000.0 -1400.000       NaN           NaN       NaN     NaN
2   1600.00  1000.0 -1500.000       NaN           NaN       NaN     NaN
3   1750.00  1000.0 -1550.000       NaN           NaN       NaN     NaN
4   1000.00  1000.0 -1300.000       NaN           NaN       NaN     NaN
5   1900.00  1000.0 -1600.000       NaN           NaN       NaN     NaN
18  2000.00  1000.0 -1575.000       NaN           NaN       NaN     NaN
19   300.00  1000.0 -1250.000       NaN           NaN       NaN     NaN
20   600.00  1000.0 -1350.000       NaN           NaN       NaN     NaN
21   900.00  1000.0  -750.000       NaN           NaN       NaN     NaN
35   600.00  1000.0  -650.000       NaN           NaN       NaN     NaN
36  1300.00  1000.0  -700.000       NaN           NaN       NaN     NaN
37  1600.00  1000.0  -800.000       NaN           NaN       NaN     NaN
38  1900.00  1000.0  -900.000       NaN           NaN       NaN     NaN
39  2000.00  1000.0  -875.000       NaN           NaN       NaN     NaN
6   1000.00  1000.0 -1000.000       NaN           NaN       NaN     NaN
7    900.00  1000.0 -1300.000       NaN           NaN       NaN     NaN
8   1100.00  1000.0  -700.000       NaN           NaN       NaN     NaN
9   1200.00  1000.0  -400.000       NaN           NaN       NaN     NaN
10   800.00  1000.0 -1600.000       NaN           NaN       NaN     NaN
41   917.45  1000.0 -1135.398 -0.948683  1.000000e-07  0.316229  71.565
17      NaN     NaN       NaN       NaN           NaN       NaN     NaN

    azimuth  polarity           formation         series  order_series  \
0       NaN       NaN           Reservoir  Default serie             1
22      NaN       NaN           Reservoir  Default serie             1
23      NaN       NaN           Reservoir  Default serie             1
24      NaN       NaN           Reservoir  Default serie             1
25      NaN       NaN           Reservoir  Default serie             1
26      NaN       NaN           Reservoir  Default serie             1
27      NaN       NaN           Reservoir  Default serie             1
28      NaN       NaN           Reservoir  Default serie             1
29      NaN       NaN           Reservoir  Default serie             1
30     90.0       1.0           Reservoir  Default serie             1
31      NaN       NaN           Reservoir  Default serie             1
32      NaN       NaN           Reservoir  Default serie             1
33      NaN       NaN           Reservoir  Default serie             1
34      NaN       NaN           Reservoir  Default serie             1
40      NaN       NaN           Reservoir  Default serie             1
11      NaN       NaN  SecondaryReservoir  Default serie             1
12      NaN       NaN  SecondaryReservoir  Default serie             1
13      NaN       NaN  SecondaryReservoir  Default serie             1
14      NaN       NaN  SecondaryReservoir  Default serie             1
15      NaN       NaN  SecondaryReservoir  Default serie             1
16      NaN       NaN  SecondaryReservoir  Default serie             1
1       NaN       NaN           Overlying  Default serie             1
2       NaN       NaN           Overlying  Default serie             1
3       NaN       NaN           Overlying  Default serie             1
4       NaN       NaN           Overlying  Default serie             1
5       NaN       NaN           Overlying  Default serie             1
18      NaN       NaN           Overlying  Default serie             1
19      NaN       NaN           Overlying  Default serie             1
20      NaN       NaN           Overlying  Default serie             1
21      NaN       NaN                Seal  Default serie             1
35      NaN       NaN                Seal  Default serie             1
36      NaN       NaN                Seal  Default serie             1
37      NaN       NaN                Seal  Default serie             1
38      NaN       NaN                Seal  Default serie             1
39      NaN       NaN                Seal  Default serie             1
6       NaN       NaN           MainFault  Default serie             1
7       NaN       NaN           MainFault  Default serie             1
8       NaN       NaN           MainFault  Default serie             1
9       NaN       NaN           MainFault  Default serie             1
10      NaN       NaN           MainFault  Default serie             1
41    270.0       1.0           MainFault  Default serie             1
17      NaN       NaN            basement  Default serie             1

    isFault  formation_number                       annotations
0     False                 1   ${\bf{x}}_{\beta \,{\bf{1}},0}$
22    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},1}$
23    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},2}$
24    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},3}$
25    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},4}$
26    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},5}$
27    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},6}$
28    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},7}$
29    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},8}$
30    False                 1   ${\bf{x}}_{\beta \,{\bf{1}},9}$
31    False                 1  ${\bf{x}}_{\beta \,{\bf{1}},10}$
32    False                 1  ${\bf{x}}_{\beta \,{\bf{1}},11}$
33    False                 1  ${\bf{x}}_{\beta \,{\bf{1}},12}$
34    False                 1  ${\bf{x}}_{\beta \,{\bf{1}},13}$
40    False                 1  ${\bf{x}}_{\beta \,{\bf{1}},14}$
11    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},0}$
12    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},1}$
13    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},2}$
14    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},3}$
15    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},4}$
16    False                 2   ${\bf{x}}_{\beta \,{\bf{2}},5}$
1     False                 3   ${\bf{x}}_{\beta \,{\bf{3}},0}$
2     False                 3   ${\bf{x}}_{\beta \,{\bf{3}},1}$
3     False                 3   ${\bf{x}}_{\beta \,{\bf{3}},2}$
4     False                 3   ${\bf{x}}_{\beta \,{\bf{3}},3}$
5     False                 3   ${\bf{x}}_{\beta \,{\bf{3}},4}$
18    False                 3   ${\bf{x}}_{\beta \,{\bf{3}},5}$
19    False                 3   ${\bf{x}}_{\beta \,{\bf{3}},6}$
20    False                 3   ${\bf{x}}_{\beta \,{\bf{3}},7}$
21    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},0}$
35    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},1}$
36    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},2}$
37    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},3}$
38    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},4}$
39    False                 4   ${\bf{x}}_{\beta \,{\bf{4}},5}$
6     False                 5   ${\bf{x}}_{\beta \,{\bf{5}},0}$
7     False                 5   ${\bf{x}}_{\beta \,{\bf{5}},1}$
8     False                 5   ${\bf{x}}_{\beta \,{\bf{5}},2}$
9     False                 5   ${\bf{x}}_{\beta \,{\bf{5}},3}$
10    False                 5   ${\bf{x}}_{\beta \,{\bf{5}},4}$
41    False                 5   ${\bf{x}}_{\beta \,{\bf{5}},5}$
17    False                 6   ${\bf{x}}_{\beta \,{\bf{6}},0}$

In [6]:
%debug

> /home/miguel/PycharmProjects/gempy/gempy/data_management.py(155)calculate_orientations()
    153         Calculate and update the orientation data (azimuth and dip) from gradients in the data frame.
    154         """
--> 155         self.orientations["dip"] = np.nan_to_num(np.arccos(self.orientations["G_z"] / self.orientations["polarity"]))
    156
    157         # TODO if this way to compute azimuth breaks there is in rgeomod=kml_to_plane line 170 a good way to do it

ipdb> self.orientations["G_z"]
0    0.948683
1    0.316229
Name: G_z, dtype: object
ipdb> self.orientations["G_z"].astype(float)
0    0.948683
1    0.316229
Name: G_z, dtype: float64
ipdb> self.orientations
        X     Y       Z       G_x    G_y       G_z     dip azimuth polarity  \
0    1450  1000   -1150  0.316229  1e-07  0.948683  18.435      90        1
1  917.45  1000 -1135.4 -0.948683  1e-07  0.316229  71.565     270        1

   formation         series  order_series  isFault  formation_number  \
0  Reservoir  Default serie             1    False                 1
1  MainFault  Default serie             1    False                 2

                       annotations
0  ${\bf{x}}_{\beta \,{\bf{1}},0}$
1  ${\bf{x}}_{\beta \,{\bf{2}},0}$
ipdb> self.orientations.dtypes
X                   object
Y                   object
Z                   object
G_x                 object
G_y                 object
G_z                 object
dip                 object
azimuth             object
polarity            object
formation           object
series              object
order_series         int64
isFault               bool
formation_number     int64
annotations         object
dtype: object
ipdb> exit

In [7]:
gp.get_data(geo_data)

              G_x  G_y  G_z     X     Y     Z azimuth  dip  formation  \
interfaces 0  NaN  NaN  NaN   300  1000  -950     NaN  NaN  Reservoir
           1  NaN  NaN  NaN  2000  1000 -1275     NaN  NaN  Reservoir
           2  NaN  NaN  NaN   NaN   NaN   NaN     NaN  NaN   basement

             polarity         series
interfaces 0      NaN  Default serie
           1      NaN  Default serie
           2      NaN  Default serie